# services:
#     php:
#         build: ./php
#         ports:
#             - 80:5000
#         volumes:
#             - ./program:/var/www/html
#     mysql:
#         build: ./mysql
#         volumes:
#             - ./baza:/var/lib/mysql

services:
    apache-php:
        build: ./php
        depends_on:
            - mysql
        ports:
            - 81:80
        volumes:
            - ./program:/var/www/html
            - ./shramba:/shramba
        restart: always

    mysql:
        image: mysql:8.2
        volumes:
            # - ./data_mysql:/var/lib/mysql
            - delilnica_sql:/var/lib/mysql
        restart: always
        environment:
            # MYSQL_ROOT_PASSWORD: IndoktrinacijaKonjukturista9181
            MYSQL_ROOT_PASSWORD: korenskogeslo
            MYSQL_DATABASE: delilnica
            MYSQL_USER: delilnica
            MYSQL_PASSWORD: FolijantPasivizem16

    phpmyadmin:
        image: phpmyadmin:5.2
        depends_on:
            - mysql
        restart: always
        ports:
            - 82:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: korenskogeslo

volumes:
    delilnica_sql:
